nut_server:
  host: 10.0.10.101
  port: 3493
  timeout: 3
notifications:
  enabled: true
  cooldown: 60
  urls:
  - url: tgram://123456789:ABCDEF1234567890/ChatID
    enabled: false
  - url: discord://your-discord-webhook-id/your-discord-webhook-token
    enabled: false
  - url: slack://your-slack-token-a/your-slack-token-b/your-slack-token-c
    enabled: false
check_interval: 5
alert_mode: basic
basic_alerts:
  battery_charge:
    enabled: true
    min: 90
    message: UPS battery charge below minimum threshold
  runtime:
    enabled: true
    min: 15
    message: UPS runtime below minimum threshold
  load:
    enabled: true
    max: 50
    message: UPS load exceeds maximum threshold
  input_voltage:
    enabled: false
    min: 110.0
    max: 130.0
    message: UPS input voltage outside acceptable range
  ups_status:
    enabled: true
    acceptable:
    - ol
    - online
    alert_when_status_changed: false
    message: UPS status not in acceptable list
formula_alert:
  expression: (battery_charge < 90 or actual_runtime_minutes < 20) and ups_load >
    20
  message: 'UPS load: {ups_load}%, charge: {battery_charge}%, runtime: {actual_runtime_minutes:.1f}
    mins'
