###############################################################################
# nut server configuration
###############################################################################

# these settings define the connection parameters to contact the nut (ups) server
nut_server:
  host: "10.0.10.101"            # ip address of the nut server
  port: 3493                     # port used for connection
  timeout: 3                     # socket connection timeout in seconds

###############################################################################
# notifications configuration
###############################################################################

# configure notification methods below; at least one must be enabled.
notifications:
  # ntfy:
  #   url: "http://your.ntfy.server.address"
  #   topic: "nutalert"
  #   tags: "ups"
  #   priority: "5"
  #   token: ""
  #   username: ""
  #   password: ""
  # apprise:
  #   url: "apprise://"
  # webhook:
  #   url: "http://your.webhook.address"
  #   headers:
  #     authorization: "your token"
  #     x-custom-header: "password123"
  tcp:
    enabled: true               # (recommended with bitvoker: https://github.com/rmfatemi/bitvoker)
    host: "10.0.10.101"         # tcp server ip to send notifications
    port: 8083                  # tcp server port

###############################################################################
# check interval and alert mode
###############################################################################

# how often to check the ups data (in seconds)
check_interval: 15

# choose alert mode: "basic" or "formula"
alert_mode: "basic"

###############################################################################
# basic alert confuguration - simple threshold-based alerts
###############################################################################

# if ANY enabled alert condition fails, an alert will be triggered (using OR logic)
basic_alerts:
  # battery charge alert
  battery_charge:
    enabled: true               # set to false to disable this check
    min: 90                     # minimum acceptable battery charge (%)
    message: "battery charge below minimum threshold"
  # runtime alert - simple threshold check
  runtime:
    enabled: true               # set to false to disable this check
    min: 15                     # minimum acceptable runtime in minutes
    message: "runtime below minimum threshold"
  # load alert - separate from runtime
  load:
    enabled: true               # set to false to disable this check
    max: 50                     # maximum acceptable load percentage
    message: "ups load exceeds maximum threshold"
  # voltage alert
  input_voltage:
    enabled: true               # set to false to disable this check
    min: 110.0                  # minimum acceptable input voltage (volts)
    max: 130.0                  # maximum acceptable input voltage (volts)
    message: "input voltage outside acceptable range"
  # status alert
  ups_status:
    enabled: true               # set to false to disable this check
    acceptable: ["ol", "online"] # acceptable ups operational statuses
    message: "ups status not in acceptable list"

###############################################################################
# advanced alert configuration - forumula-based alerts
###############################################################################

# formula mode: create a custom formula using ups data
# available variables for your formula:
#   ups_load - current ups load percentage
#   battery_charge - current battery charge percentage
#   actual_runtime_minutes - current battery runtime in minutes
#   battery_voltage - current battery voltage
#   input_voltage - current input voltage
#   ups_status - current ups status string (lowercase)

# your formula should return True to trigger an alert
# examples:
# - simple condition check: "battery_charge < 90 or ups_status != 'ol'"
# - load-based runtime: "actual_runtime_minutes < (60 if ups_load <= 15 else (30 if ups_load >= 50 else 60 - (ups_load * 0.6)))"
# - complex calculation: "(battery_charge / 100.0) * (battery_voltage / input_voltage) * (actual_runtime_minutes / 60) < 0.5"
formula_alert:
  expression: "(battery_charge < 90 or actual_runtime_minutes < 20) and ups_load > 20"
  message: "ups alert: custom formula conditions not met"
